<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}" />
        <meta http-equiv="refresh" content="3">
        <title>Finalisation de l'abonnement</title>
        @vite(['resources/scss/app.scss', 'resources/js/app.js'])

        <style type="text/css">
            @keyframes ldio-rfp2roz9c4 {
              0% { opacity: 1 }
              100% { opacity: 0 }
            }
            .ldio-rfp2roz9c4 div {
              left: 94px;
              top: 48px;
              position: absolute;
              animation: ldio-rfp2roz9c4 linear 1s infinite;
              background: #fe718d;
              width: 12px;
              height: 24px;
              border-radius: 6px / 12px;
              transform-origin: 6px 52px;
            }.ldio-rfp2roz9c4 div:nth-child(1) {
              transform: rotate(0deg);
              animation-delay: -0.9166666666666666s;
              background: #fe718d;
            }.ldio-rfp2roz9c4 div:nth-child(2) {
              transform: rotate(30deg);
              animation-delay: -0.8333333333333334s;
              background: #fe718d;
            }.ldio-rfp2roz9c4 div:nth-child(3) {
              transform: rotate(60deg);
              animation-delay: -0.75s;
              background: #fe718d;
            }.ldio-rfp2roz9c4 div:nth-child(4) {
              transform: rotate(90deg);
              animation-delay: -0.6666666666666666s;
              background: #fe718d;
            }.ldio-rfp2roz9c4 div:nth-child(5) {
              transform: rotate(120deg);
              animation-delay: -0.5833333333333334s;
              background: #fe718d;
            }.ldio-rfp2roz9c4 div:nth-child(6) {
              transform: rotate(150deg);
              animation-delay: -0.5s;
              background: #fe718d;
            }.ldio-rfp2roz9c4 div:nth-child(7) {
              transform: rotate(180deg);
              animation-delay: -0.4166666666666667s;
              background: #fe718d;
            }.ldio-rfp2roz9c4 div:nth-child(8) {
              transform: rotate(210deg);
              animation-delay: -0.3333333333333333s;
              background: #fe718d;
            }.ldio-rfp2roz9c4 div:nth-child(9) {
              transform: rotate(240deg);
              animation-delay: -0.25s;
              background: #fe718d;
            }.ldio-rfp2roz9c4 div:nth-child(10) {
              transform: rotate(270deg);
              animation-delay: -0.16666666666666666s;
              background: #fe718d;
            }.ldio-rfp2roz9c4 div:nth-child(11) {
              transform: rotate(300deg);
              animation-delay: -0.08333333333333333s;
              background: #fe718d;
            }.ldio-rfp2roz9c4 div:nth-child(12) {
              transform: rotate(330deg);
              animation-delay: 0s;
              background: #fe718d;
            }
            .loadingio-spinner-spinner-redukw5dnl {
              width: 200px;
              height: 200px;
              display: inline-block;
              overflow: hidden;
              background: #ffffff;
            }
            .ldio-rfp2roz9c4 {
              width: 100%;
              height: 100%;
              position: relative;
              transform: translateZ(0) scale(1);
              backface-visibility: hidden;
              transform-origin: 0 0; /* see note above */
            }
            .ldio-rfp2roz9c4 div { box-sizing: content-box; }
            /* generated by https://loading.io/ */
            </style>
    </head>

    <body id="backEndUser">

    <div class="container mt-3">

        <div class="d-flex justify-content-center mb-3">
           
            <div>
              <img class="img-fluid" src="{{asset('img/deco/logo-mail.png')}}" alt="" width="250">
            </div>
    
        </div>

        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
       
                    <div class="card-body text-center">
       
                        <div class="pt-3 mb-3">
                            <h5>Finalisation de l'abonnement. Veuillez patienter...</h5>
                        </div>
    
                        <div>
                            <div class="loadingio-spinner-spinner-redukw5dnl"><div class="ldio-rfp2roz9c4">
                            <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div>
                            </div><div></div><div></div><div></div><div></div></div></div>
                        </div>
    
                        
       
                    </div>
               </div>
        </div>
    </div>

</body>
</html>
