<p>Les présentes Conditions Générales de Vente sont à jour au 01 janvier 2023.</p>
<p>Entre :</p>
<p>ET BAM Solutions – SAS au capital social de 1000 euros, domiciliée au 33 rue Claire Joie, 83200 Toulon – {{ config('app.url') }} – R.C.S 983 750 118 R.C.S. Toulon  – Siren 983 750 118.</p>
<p>Ci-après « ET BAM Solutions »</p>
<p>Et :</p>
<p>Ci-après « le Client »</p>
<p>Ensemble dénommées “les Parties” et séparément “une Partie”</p>
<p>ET BAM Solutions a pour activité la création et le développement d’un logiciel accessible depuis le site internet {{ config('app.url') }} (ci-après le Site) pour les enseignant(e)s de classe de maternelle.</p>
<h5 class="mt-3">ARTICLE 1 - Dispositions générales</h5>
<p>1.1 Le terme " Client “ désigne toute personne, morale ou physique, ayant souscrit à l’offre d’abonnement.</p>
<p>1.2 Le terme “ Consommation ” désigne toute action du Client qui s’apparente à une utilisation de l’abonnement, notamment le fait de se loguer sur la plateforme, d’y mettre à jour des données, de poser une question au support client, sans que cette liste soit exhaustive.</p>
<p>1.3 Le terme " Tiers " désigne toute personne physique ou morale non-partie aux présentes Conditions Générales de Vente (CGV).</p>
<p>1.4 Le terme “ Site “ désigne le site internet commercial de la société ET BAM Solutions (accessible à l’adresse {{ config('app.url') }}).</p>
<p>1.5 Le terme “ Service “ désigne l’ensemble des offres détaillées sur le site {{ config('app.url') }}</p>
<p>1.6 Les présentes CGV régissent la relation contractuelle entre les Parties. Elles s’appliquent aux seuls professionnels à l’exclusion des consommateurs. A ce titre, le Client reconnaît avoir la qualité de professionnel, conformément aux dispositions du Code de la consommation applicables. Le Client reconnaît également avoir le pouvoir pour engager la société partie au Contrat.</p>
<p>1.7 Les présentes CGV se substituent à tout autre document antérieur ou tout autre accord écrit ou verbal en relation avec le même objet, et prévaut sur toute disposition contraire qui pourrait être contenue dans les documents émanant du Client.</p>
<p>1.8 Si l’une quelconque disposition de ces CGV ou son application à toute personne ou circonstance est jugée nulle, cette nullité ne concernera pas les autres dispositions ou applications de ces CGV, qui resteront en vigueur indépendamment de la disposition jugée nulle. A cette fin, les dispositions de ces CGV sont déclarées autonomes.</p>
<p>1.9 Les CGV sont rédigées en langue française.</p>
<h5 class="mt-3">ARTICLE 2 – Moyens techniques - Caractéristiques du service</h5>
<p>2.1 Avant toute utilisation du Site et du service, le Client doit s’assurer qu’il dispose des moyens techniques et informatiques lui permettant d’utiliser le Site et de commander les services sur le Site. Le Client doit également s’assurer que la configuration informatique de son matériel/équipement est en bon état de fonctionnement, qu’il ne contient pas de virus et que son navigateur permet un accès sécurisé au Site.</p>
<p>2.2 Le service est accessible en ligne. Il donne accès aux fonctionnalités précisément détaillées préalablement à la souscription du service sur le Site, et récapitulées au moment de celle-ci</p>
<h5 class="mt-3">ARTICLE 3 - Objet</h5>
<p>3.1 Les présentes CGV ont pour objet de déterminer les conditions dans lesquelles ET BAM Solutions consent au Client, qui l’accepte, le droit incessible, non exclusif et personnel d’utiliser le service dont les caractéristiques sont précisées au précédent article.</p>
<p>3.2 ET BAM Solutions se réserve expressément, sans indemnisation, le droit de modifier, à des fins d’amélioration, sans préavis et à tout moment tout ou partie du service ou ses modalités d’accès et, le cas échéant, la présentation et/ou le contenu des fonctionnalités.</p>
<p>3.3 Les CGV sont systématiquement adressées ou remises à chaque Client avant la souscription au service. En conséquence, le fait de cliquer sur le bouton cliquable « S’abonner » après avoir renseigné ses coordonnées pour créer son compte sur le site, enregistré sa carte bancaire auprès du prestataire de paiement,  et pris connaissance des CGV atteste de l’adhésion entière et sans réserve du Client aux présentes, à l’exclusion de tous autres documents en sa possession tels que catalogues ou plaquettes publicitaires émis par ET BAM Solutions, lesquels n’auront qu’une valeur indicative et non contractuelle.</p>
<h5 class="mt-3">ARTICLE 4 - Accès au service</h5>
<p>4.1 Le Client accède au service en ligne par Internet, par le biais du Site, à l’aide d’un identifiant et d’un mot de passe choisis à la création de son compte.</p>
<p>4.2 Le Client aura ainsi accès au service en mode SaaS 24h/24 et 7j/7 sauf en cas d’opérations de maintenance, pannes éventuelles ou force majeure affectant ET BAM Solutions.</p>
<p>4.3 Le Client fait son affaire de souscrire, auprès d’un fournisseur d’accès à Internet, un abonnement lui permettant d’accéder au Site et au service. Le Client s’assure de la compatibilité de son environnement technique requise pour l’accès et/ou l’utilisation du service.</p>
<p>4.4 L’abonnement au service souscrit par le Client est uniquement valable pour ses représentants et ses salariés et ne peut en aucun cas être utilisé par un Tiers. Le Client reconnaît que les codes d’accès au service sont strictement personnels, confidentiels et intransmissibles. Le Client s’engage à préserver la confidentialité de ses codes d’accès au service et à prendre toute mesure nécessaire afin d’empêcher la communication desdits codes qui permettrait à des Tiers d’accéder au service.</p>
<p>4.5 Le Client s’engage à ne pas revendre les prestations incluses dans le service à ses clients ou à des Tiers. En cas de non-respect de cette obligation, ET BAM Solutions pourra procéder à la suspension immédiate de l’exécution de ses prestations, sans avoir à en justifier auprès du Client, voire à la résiliation pour faute du contrat, dans les conditions prévues à l’article 7 des présentes.</p>
<h5 class="mt-3">ARTICLE 5 - Mises à jour - Maintenance</h5>
<p>5.1 Le service accessible par le biais du Site fait l’objet de mises à jour régulières par ET BAM Solutions, ainsi que des opérations de maintenance à des fins évolutives et/ou correctives.</p>
<p>5.2 ET BAM Solutions s’engage à faire son possible pour que ces opérations ne perturbent pas l’utilisation du Client. Lorsque les opérations de maintenance ou de mise à jour sont susceptibles d’entraîner la suspension du service, ET BAM Solutions s’engage à en notifier le Client dans les meilleurs délais, et préalablement à la mise en œuvre de ladite opération.</p>
<h5 class="mt-3">ARTICLE 6 - Durée - Service de gestion d’une classe de maternelle</h5>
<p>6.1 Abonnements à paiement annuel : Le contrat souscrit entre les Parties prend effet à compter de la date d’activation du service pour la durée initiale et ferme (« Durée initiale ») d’un (1) an. Au terme de cette Durée initiale, le contrat se renouvelle par tacite reconduction pour la même durée et de ce fait de nouveaux droits d’abonnement seront automatiquement débités sur le compte du client.</p>
<p>6.4 Résiliation des abonnements à paiement annuel : Le contrat pourra être résilié à tout moment par le Client dans son espace personnel. Le montant total du prix de l’abonnement annuel reste dû à la Société, dès lors que celui-ci a déjà débuté au moment de la résiliation.</p>
<h5 class="mt-3">ARTICLE 7 - Résiliation</h5>
<p>7.1 Sous réserve des dispositions d’ordre public, ET BAM Solutions et le Client pourront résilier le Contrat en cas de faute grave, non réparée dans les quinze (15) jours suivant mise en demeure, sous réserve de notifier leur décision à l’autre Partie, par lettre recommandée avec accusé de réception.</p>
<p>7.2 Constitue une faute grave au sens de l’article précédent, sans que cette liste ne soit exhaustive :</p>
<ul>
<li>le fait pour une Partie de ne pas remédier à un manquement contractuel dans un délai de quinze (15) jours suivant la lettre de mise en demeure envoyée par lettre recommandée avec accusé de réception,</li>
<li>le non-règlement d’une facture à son échéance, que celui-ci soit total ou partiel,</li>
<li>la violation par le Client du périmètre des droits qui lui sont concédés en application du contrat,</li>
<li>une tentative d’intrusion ou d’atteinte à l’intégrité du Site par le Client</li>
<li>la communication par le Client de ses codes d’accès à des Tiers.</li>
</ul>
<p>7.3 En cas de résiliation anticipée du contrat aux torts du Client et ce, quelle qu’en soit la cause, toutes les sommes restantes dues par le Client seront immédiatement exigibles sans préjudice des dommages et intérêts qui pourraient être dus à ET BAM Solutions. Par ailleurs, la Partie défaillante s’engage à indemniser l’autre Partie pour tous les dommages prouvés qu’elle a subis et résultant de la résiliation du contrat du fait d’un manquement de la Partie défaillante à ses obligations contractuelles.</p>
<h5 class="mt-3">ARTICLE 8 - Prix - Commande - Paiement</h5>
<p><strong>Prix</strong></p>
<p>8.1 ET BAM Solutions offre au Client la possibilité de tester le service au travers d’un “Mode découverte” limité à 10 évaluations pour sa classe. Toutes les fonctions du service sont disponibles.</p>
<p>8.2 En contrepartie de l’accès au service en “Mode Premium” dans les conditions prévues par les présentes, le Client s’engage à payer à ET BAM Solutions une rémunération d’utilisation du service. En cas de résiliation anticipée du Contrat pour quelque cause que ce soit, le Client s’engage à régler à ET BAM Solutions l’intégralité des sommes restant dues au titre de la redevance du Service.</p>
<p>8.3 Le montant de la rémunération du service est indiqué sur le Site et précisément sur la <a href="{{ route('mf.tarifs') }}">page tarifs</a>, en euros, hors taxes et toutes taxes comprises. Les tarifs indiqués sur le Site sont ceux en vigueur le jour de la souscription de l’abonnement.</p>
<p>8.4 Le montant de la rémunération du service est payable lors de la souscription de l’abonnement, puis selon les conditions définies à l’article 6 ci-dessus. Le règlement de la rémunération du service s’opérera via notre solution de paiement sécurisée qui offre plusieurs modes de paiement. Les sommes dues à ET BAM Solutions ne comprennent pas le coût de la connexion Internet qui reste à la charge du Client.</p>
<p>8.5 ET BAM Solutions pourra modifier le montant de la rémunération du service sous réserve d’informer par tous moyens le Client au moins quinze (15) jours avant l’entrée en vigueur de cette modification tarifaire. La nouvelle rémunération du service ne s’applique qu’à la reconduction du service : le mois suivant la notification au Client pour les forfaits à paiement mensuel, l’année suivant la notification au Client pour les forfaits à paiement annuel. Le Client est libre de s’opposer au changement de tarif en résiliant son abonnement depuis son compte personnel dans un délai de quinze (15) jours suivant la notification au Client. A défaut de demande de résiliation dans ce délai, le Client est réputé avoir accepté la nouvelle rémunération du service.</p>
<p><strong>Commande</strong></p>
<p>8.6 Le Service est fourni sous réserve que le Client accepte les présentes CGV, dans les conditions prévues à l’article 3.3 ci-dessus, outre la politique de protection des données personnelles de ET BAM Solutions, également présentée avant la validation de la commande.
Le Client est réputé avoir pris connaissance et accepté les présentes CGV et la Politique de protection des données, par le biais d’un bouton cliquable « S’abonner » lors de la commande du Service.</p>
<p>8.7 Après acceptation des présentes CGV, de la politique de protection des données personnelles, et validation de la commande, le contrat est valablement conclu entre ET BAM Solutions et le Client, et les engage de manière irrévocable. Un email de confirmation de la commande est alors envoyé au Client.</p>
<p>8.8 ET BAM Solutions recommande au Client de conserver les informations contenues dans la confirmation de sa commande établie à son attention par ET BAM Solutions, sur support papier ou sur support informatique.</p>
<p>8.9 Les commandes passées par le Client sont donc fermes et irrévocables et sont soumises aux présentes CGV.</p>
<p>8.10 ET BAM Solutions se réserve le droit d’annuler ou de refuser toute commande qui émanerait d’un Client avec lequel il existerait un litige relatif au paiement d’une précédente commande.</p>
<p><strong>Paiement</strong></p>
<p>8.11 Les prix sont mentionnés sur le Site dans les descriptifs du service, en euros, hors taxes et toutes taxes comprises.</p>
<p>8.12 Le montant total de la commande est indiqué dans le récapitulatif, avant que le Client n’accepte les présentes CGV, valide sa commande de service, renseigne et valide ses coordonnées de facturation et procède au paiement. Ce montant total est indiqué en hors taxes et toutes taxes comprises.</p>
<p>8.13 La commande du service sur le Site est payable en euros. La totalité du paiement doit être réalisée au jour de la commande par le Client.</p>
<p>8.14 Le Site utilise le système de sécurisation de Stripe pour le paiement par carte bancaire, prestataire spécialisé dans la sécurisation de paiement en ligne. Ces systèmes garantissent au Client la totale confidentialité de ses informations bancaires. La transaction bancaire, réalisée entre le Client et le système sécurisé choisi est donc entièrement cryptée et protégée. Les coordonnées bancaires du Client ne sont pas stockées informatiquement par ET BAM Solutions.</p>
<p>8.15 Le Client ne pourra, sous aucun prétexte, procéder à une quelconque déduction entre les sommes que ET BAM Solutions pourrait lui devoir et les sommes qu’il devra à ET BAM Solutions, sauf accord exprès de ce dernier pour y procéder. Dans la mesure où elle sera applicable, la TVA sera ajoutée par ET BAM Solutions aux montants facturés.</p>
<p>8.16 ET BAM Solutions se réserve le droit de suspendre ou d’annuler toute exécution du service en cas de défaut de paiement ou de paiement partiel de toute somme qui serait due par le Client à ET BAM Solutions. En cas de non-paiement d’une facture à sa date d’échéance, un intérêt au taux légal en vigueur augmenté de quatre (4) points sera automatiquement appliqué par ET BAM Solutions jusqu’au complet paiement, et, ce, sans notification préalable.</p>
<p>8.17 Conformément aux articles L.441-10 du Code du commerce et D.441-5 du Code du commerce, tout retard de paiement entraîne de plein droit, outre les pénalités de retard, une obligation pour le Client de payer une indemnité forfaitaire de quarante (40) euros pour frais de recouvrement. Lorsque les frais de recouvrement exposés sont supérieurs au montant de cette indemnité forfaitaire, ET BAM Solutions pourra demander une indemnisation complémentaire, sur justification.</p>
<p>8.18 Le Client est informé qu’aucun escompte ne sera consenti en cas de paiement anticipé.</p>
<h5 class="mt-3">ARTICLE 9 - Réclamation</h5>
<p>9.1 La Société s’engage à répondre à toute réclamation dans un délai maximum de dix (10) jours ouvrés à compter de la réception d’une demande écrite adressée à via notre formulaire de contact.</p>
<h5 class="mt-3">ARTICLE 10 - Garantie et responsabilité</h5>
<p>10.1 Le Client est seul responsable de l’usage qu’il fait du service, notamment l’utilisation et l’interprétation des informations mises à sa disposition par ET BAM Solutions ainsi que des actes et conseils qu’il en déduit dans le cadre de sa pratique professionnelle. ET BAM Solutions ne sera tenu que des garanties légales applicables à son service le cas échéant, à l’exclusion de toute autre garantie.</p>
<p>10.2 ET BAM Solutions sera responsable de sa négligence et de ses fautes, ainsi que de celles de ses préposés, si l’une de ces négligences ou fautes est susceptible de causer le décès d’une personne ou de la blesser.</p>
<p>10.3 La responsabilité de ET BAM Solutions, au titre des dommages directs et prouvés causés au Client, est limitée au montant de la commande en cause. En aucun cas, ET BAM Solutions ne sera tenu pour responsable des dommages indirects, accessoires ou particuliers tels que définis par la jurisprudence des tribunaux français.</p>
<p>10.4 ET BAM Solutions ne pourra en aucun cas être tenue pour responsable : (i) des dommages dus à l’inexécution par le Client de ses obligations ; (ii) de tout préjudice financier ou commercial tel que, par exemple les pertes de bénéfice, les pertes de clientèle, les pertes de données, les troubles commerciaux quelconques, les pertes de commandes, qui constituent des dommages imprévisibles et indirects et par conséquent n’ouvrent pas de droit à réparation.</p>
<p>10.5 ET BAM Solutions ne peut être tenue pour responsable de l’inexécution du contrat en cas de force majeure telle que définie par l’article 1218 du Code civil et les tribunaux français, et en cas de dommages du fait d’un tiers ou imputables à une mauvaise utilisation ou une utilisation non-conforme par le Client des services, en violation des prescriptions de ET BAM Solutions ou des règles de l’art.</p>
<h5 class="mt-3">ARTICLE 11 - Droit d’utilisation et de reproduction</h5>
<p>11.1 Le service, de même que l’intégralité des données figurant sur le Site, est protégé par le droit d’auteur et par le droit des bases de données conformément au code de la propriété intellectuelle. Ces éléments ne peuvent en aucun cas faire l’objet, même partiellement, de reproduction, représentation, prêt, échange, vente, distribution ou transmission à l’exception des cas expressément autorisés par la loi ou prévus au contrat. Les fonctionnalités du service ne sauraient être utilisées à des fins de violation ou de détournement de ces droits de propriété intellectuelle.</p>
<p>11.2 Le Client s’interdit tout usage du service à des fins autres que celles expressément prévues au contrat, de même qu’il s’interdit de diffuser, publier, vendre ou d’échanger de quelque manière que ce soit, les contenus auxquels il accède et plus généralement de porter atteinte, directement ou indirectement, de quelque façon que ce soit aux droits de ET BAM Solutions.</p>
<p>11.3 Le Client s’engage à ne pas reconstituer ou tenter de reconstituer, à partir des données et/ou au moyen du service, une base de données visant à offrir, directement ou indirectement, à titre gratuit ou à titre onéreux, le même service ou un service comparable, à toutes personnes tierces à son entreprise dans le but de contourner la personnalisation d’accès au service dont il bénéficie.</p>
<p>11.4 Le Client s’engage plus généralement à ne pas porter atteinte aux droits de propriété intellectuelle détenus par ET BAM Solutions sur le service ou tout autre élément figurant sur le Site protégé par un droit de propriété intellectuelle, en ce compris les marques et logos.</p>
<h5 class="mt-3">ARTICLE 12 - Confidentialité des données du Client</h5>
<p>Les dispositions concernant la protection des données personnelles telles qu’issues de la Loi Informatique et Libertés en date du 6 janvier 1978 modifiée, et du Règlement européen sur la protection des données personnelles (« RGPD ») sont situées dans un document annexe intitulé <a href="{{ route('mf.confidentialite') }}">« Politique de Confidentialité »</a></p>
<h5 class="mt-3">ARTICLE 13 – Dispositions générales</h5>
<p>13.1 Droit applicable : Le contrat est interprété et régi conformément au droit français sans tenir compte des principes de conflits de lois.</p>
<p>13.2 Attribution de compétence : Seront seuls compétents pour connaître des litiges de toutes natures ou de contestations relatives à l’interprétation ou à l’exécution des présentes CGV, les Tribunaux du ressort de la Cour d’appel de Aix-en-Provence, nonobstant pluralité de défendeurs, demande incidente ou référé ou appels en garantie, à moins que ET BAM Solutions ne préfère saisir toute autre juridiction compétente.</p>
<p>13.3 Cession : ET BAM Solutions peut décider de céder ou transférer les droits ou obligations que lui confèrent les présentes CGV sous réserve que le Client bénéficie des mêmes obligations que ET BAM Solutions et, ce, dans les mêmes conditions.</p>
<p>13.4 Convention de preuve : Les Parties conviennent que tous les écrits, notamment l’écrit électronique, échangés entre eux ainsi que toutes données, notamment techniques, font foi et prouvent valablement la teneur de leurs échanges et de leurs engagements.</p>
<p>13.5 Contact : ET BAM Solutions peut être contactée, à tout moment, par le formulaire de contact accessible au lien suivant : <a href="{{ route('mf.contact') }}">formulaire de contact</a></p>